version: '3.10.9.{build}'
branches:
  only:
    - /v3.10.9/
    - dev
cache:
  - '%LOCALAPPDATA%\pip\Cache'
environment:
  APPVEYOR_OS: 'windows'
  global:
    WITH_COMPILER: 'cmd /E:ON /V:ON /C .\ci\appveyor-with-compiler.cmd'

  matrix:

    - TOXENV: "py37"
      TOXPYTHON: "C:\\Python37-x64\\python.exe"
      PYTHON_HOME: "C:\\Python37-x64"
      PYTHON_VERSION: "3.7"
      PYTHON_ARCH: "64"

    - TOXENV: "py36"
      TOXPYTHON: "C:\\Python36\\python.exe"
      PYTHON_HOME: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"

init:
  - "ECHO %TOXENV%"
  - "ECHO %PYTHON_HOME%"
  - "ECHO %TOXPYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - ps: (new-object net.webclient).DownloadFile('https://bootstrap.pypa.io/get-pip.py', 'C:/get-pip.py')
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%\Scripts;%PATH%
  - "ECHO %PATH%"
  - "%TOXPYTHON% C:/get-pip.py"
  - "%PYTHON_HOME%/Scripts/pip.exe install -r requirements-appveyor.txt"
  - "%TOXPYTHON% -m pip install tox"


build: false  # First tests then build (is python not C)

test_script:
  - "%TOXPYTHON% -m tox -e %TOXENV%"

on_failure:
  - ps: dir "env:"
