default_language_version:
  python: python3.6

fail_fast: true

repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: 'v0.27.0'
  hooks:
  - id: yapf
    name: 'Google yapf formatting'
# - repo: https://github.com/pre-commit/mirrors-isort
#   rev: 'v4.3.18'
#   hooks:
#   - id: isort
#     exclude: '__init__.py'
#     name: 'Reorder python imports'
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 'v1.4.0'
  hooks:
  - id: python-no-log-warn
    name: 'Use logger.warning('
  - id: python-no-eval
    name: 'Check for eval()'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v2.2.1'
  hooks:
  - id: fix-encoding-pragma
  - id: check-docstring-first
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: '.*\.md'
  - id: requirements-txt-fixer
  - id: flake8
    name: 'Lint and check style with Flake8'
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: 'v2.3.1'
  hooks:
  - id: pylint
    name: 'Lint with Pylint'
- repo: local
  hooks:
  - id: radon
    name: 'Caculating Maintainability Index'
    entry: radon mi -s
#   entry: radon mi isbnlib -s -e "*_data/*"
    language: python
    additional_dependencies: [radon]
