default_language_version:
  python: python3.6

fail_fast: true

repos:
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: 'v0.27.0'
  hooks:
  - id: yapf
- repo: https://github.com/pre-commit/mirrors-isort
  rev: 'v4.3.18'
  hooks:
  - id: isort
    exclude: '__init__.py'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v2.2.1'
  hooks:
  - id: fix-encoding-pragma
  - id: check-docstring-first
  - id: mixed-line-ending
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    exclude: '.*\.md'
  - id: flake8
- repo: https://github.com/pre-commit/mirrors-pylint
  rev: 'v2.3.1'
  hooks:
  - id: pylint
