sudo: false
language: python
branches:
  only:
  - dev
  - master
  - v3.9.6
matrix:
  include:
  - os: osx
    language: generic
    env: TOXENV=py36
  - python: "2.7"
    env: TOXENV=py27
# - python: "3.7"
#   env: TOXENV=py37
  - python: "3.6"
    env: TOXENV=py36
  - python: "3.5"
    env: TOXENV=py35
  - python: "3.4"
    env: TOXENV=py34
  - python: "nightly"
    env: TOXENV=nightly
  - python: "2.7"
    env: TOXENV=checkers
  - python: "2.7"
    env: DOC=sphinx
  allow_failures:
  - env: TOXENV=nightly
  - env: TOXENV=py34
install:
#- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew upgrade python && python3 --version; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then python3 --version; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then pip3 install tox; fi
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then pip install tox; fi
- if [[ $TOXENV == 'py27' ]]; then pip install coveralls; fi
- if [[ $DOC == 'sphinx' ]]; then pip install sphinx; fi
script:
#- if [[ $TRAVIS_PULL_REQUEST != 'false' ]]; then ...; fi
- if [[ ! -z $TOXENV ]]; then tox -e $TOXENV; fi
- if [[ $DOC == 'sphinx' ]]; then cd docs; sphinx-build -n -b html -d _build/.doctrees . _build/html; fi
after_success:
- if [[ $TOXENV == 'py27' ]]; then coveralls; fi
notifications:
  email: false
